spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6380
      password: ${REDIS_PASSWORD}
      username: default
server:
  forward-headers-strategy: framework
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
management:
  metrics:
    enable:
      processor: false
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG