-- Baseline: the schema as it was built by ddl-auto before Flyway was introduced.
-- Users, volunteers, organizations and the skill dictionary.

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE app_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    password   VARCHAR(255),
    is_banned  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    CONSTRAINT uq_app_users_username UNIQUE (username),
    CONSTRAINT uq_app_users_email UNIQUE (email)
);

CREATE TABLE user_role (
    user_id BIGINT       NOT NULL,
    roles   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, roles),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_role_roles CHECK (roles IN ('ROLE_VOLUNTEER', 'ROLE_ORGANIZATION'))
);

-- A volunteer shares its primary key with the user account.
CREATE TABLE volunteers (
    id            BIGINT PRIMARY KEY,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    date_of_birth DATE,
    location      geometry(Point, 4326),
    location_name VARCHAR(255),
    country_code  VARCHAR(2),
    city          VARCHAR(255),
    region        VARCHAR(255),
    radius        INTEGER,
    CONSTRAINT fk_volunteers_user FOREIGN KEY (id) REFERENCES app_users (id) ON DELETE CASCADE
);

-- An organization shares its primary key with the user account (changed in Slice 2).
CREATE TABLE organizations (
    id                BIGINT PRIMARY KEY,
    organization_name VARCHAR(255) NOT NULL,
    description       TEXT,
    website_url       VARCHAR(255),
    location          geometry(Point, 4326),
    city              VARCHAR(255),
    full_address      VARCHAR(255),
    country_code      VARCHAR(255),
    CONSTRAINT fk_organizations_user FOREIGN KEY (id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE skills (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(255) NOT NULL,
    category   VARCHAR(255) NOT NULL,
    CONSTRAINT uq_skills_skill_name UNIQUE (skill_name),
    CONSTRAINT ck_skills_category CHECK (category IN ('SOCIAL', 'IT', 'LOGISTICS', 'MEDICINE'))
);
